    name: qa-practice-tests
    on:
        push:
        schedule:
            - cron: '0 10 * * *' # Runs at 11:00 BST (10:00 UTC) every day
    jobs:
        cypress-run:
            runs-on: ubuntu-latest
            steps:
            - name: Checkout
                uses: actions/checkout@v3
            - name: Cypress run
                uses: cypress-io/github-action@v5
                with:
                start: npx cypress run
            - name: Save HTML Report
                uses: actions/upload-artifact@v3
                if: always()
                with:
                name: cypress-report
                path: ./**/cypress/reports


                //this is a project of new branch
